WITH SALES_INFO AS (
    SELECT BOOK_ID, SUM(SALES) AS SALES_SUM
    FROM BOOK_SALES
    WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-01'
    GROUP BY BOOK_ID
)

SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM((SI.SALES_SUM * B.PRICE)) AS TOTAL_SALES
FROM BOOK AS B
    JOIN SALES_INFO AS SI ON B.BOOK_ID = SI.BOOK_ID
    JOIN AUTHOR AS A ON B.AUTHOR_ID = A.AUTHOR_ID
GROUP BY A.AUTHOR_NAME, B.CATEGORY
ORDER BY A.AUTHOR_ID, B.CATEGORY DESC