SELECT p.PRODUCT_CODE, (SUM(o.SALES_AMOUNT) * p.PRICE) AS SALES
FROM PRODUCT AS p
    INNER JOIN OFFLINE_SALE AS o ON p.PRODUCT_ID = o.PRODUCT_ID
GROUP BY p.PRODUCT_CODE
ORDER BY SALES DESC, p.PRODUCT_CODE ASC;