SELECT DISTINCT INFO.CAR_ID, INFO.CAR_TYPE, 30 * (INFO.DAILY_FEE * (1 - DISCOUNT.DISCOUNT_RATE / 100)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS INFO
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS DISCOUNT
    ON INFO.CAR_TYPE = DISCOUNT.CAR_TYPE
WHERE (INFO.CAR_TYPE = '세단' OR INFO.CAR_TYPE = 'SUV')
    AND DISCOUNT.DURATION_TYPE = '30일 이상'
    AND INFO.CAR_ID NOT IN (
        SELECT HISTORY.CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS HISTORY
        WHERE (HISTORY.START_DATE <= '2022-11-30'
               AND HISTORY.END_DATE >= '2022-11-01')
    )
    AND (30 * (INFO.DAILY_FEE * (1 - DISCOUNT.DISCOUNT_RATE / 100)) >= 500000
        AND 30 * (INFO.DAILY_FEE * (1 - DISCOUNT.DISCOUNT_RATE / 100)) <= 2000000)
ORDER BY FEE DESC, INFO.CAR_TYPE, INFO.CAR_ID;