# SELECT * FIRST_HALF AS f
# INNER JOIN JULY AS j ON 
# f.TOTAL_ORDER, 
# ORDER BY  LIMIT 3;

SELECT j.FLAVOR FROM JULY AS j
INNER JOIN FIRST_HALF AS f ON j.FLAVOR = f.FLAVOR
GROUP BY j.FLAVOR
ORDER BY SUM(j.TOTAL_ORDER) + f.TOTAL_ORDER DESC
LIMIT 3;