-- 코드를 작성해주세요
SELECT DISTINCT d.ID, d.EMAIL, d.FIRST_NAME, d.LAST_NAME
FROM DEVELOPERS AS d,
    SKILLCODES AS s
WHERE (s.NAME = 'Python' AND s.CODE & d.SKILL_CODE > 0)
    OR (s.NAME = 'C#' AND s.CODE & d.SKILL_CODE > 0)
ORDER BY d.ID;