-- 코드를 입력하세요
SELECT i.INGREDIENT_TYPE, SUM(h.TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF as h
    INNER JOIN ICECREAM_INFO as i
    ON h.FLAVOR = i.FLAVOR
GROUP BY i.INGREDIENT_TYPE
ORDER BY TOTAL_ORDER;